# Generated by Django 6.0.7 on 2026-07-22 15:29

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Promotion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=150, verbose_name='ชื่อโปรโมชั่น')),
                ('promotion_type', models.CharField(choices=[('COUPON', 'คูปองส่วนลด'), ('STOREWIDE', 'ลดทั้งร้าน'), ('THRESHOLD', 'ซื้อครบรับส่วนลด'), ('FREE_SHIPPING', 'ส่งฟรี'), ('SEASONAL', 'โปรโมชั่นตามเทศกาล'), ('MEMBER', 'โปรโมชั่นสำหรับสมาชิก')], max_length=30, verbose_name='ประเภทโปรโมชั่น')),
                ('code', models.CharField(blank=True, help_text='กรอกเฉพาะโปรโมชั่นประเภทคูปอง เช่น WELCOME10', max_length=50, null=True, unique=True, verbose_name='รหัสคูปอง')),
                ('discount_type', models.CharField(choices=[('PERCENT', 'เปอร์เซ็นต์'), ('FIXED', 'จำนวนเงิน'), ('NONE', 'ไม่มีส่วนลดสินค้า')], default='PERCENT', max_length=20, verbose_name='รูปแบบส่วนลด')),
                ('discount_value', models.DecimalField(decimal_places=2, default=0, max_digits=10, verbose_name='มูลค่าส่วนลด')),
                ('minimum_subtotal', models.DecimalField(decimal_places=2, default=0, max_digits=10, verbose_name='ยอดซื้อขั้นต่ำ')),
                ('maximum_discount', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True, verbose_name='ส่วนลดสูงสุด')),
                ('starts_at', models.DateTimeField(blank=True, null=True, verbose_name='วันเริ่มใช้งาน')),
                ('ends_at', models.DateTimeField(blank=True, null=True, verbose_name='วันสิ้นสุด')),
                ('usage_limit', models.PositiveIntegerField(blank=True, null=True, verbose_name='จำนวนสิทธิ์ทั้งหมด')),
                ('used_count', models.PositiveIntegerField(default=0, editable=False, verbose_name='ใช้ไปแล้ว')),
                ('priority', models.PositiveIntegerField(default=100, help_text='ตัวเลขน้อยมีความสำคัญสูงกว่า', verbose_name='ลำดับความสำคัญ')),
                ('is_active', models.BooleanField(default=True, verbose_name='เปิดใช้งาน')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'โปรโมชั่น',
                'verbose_name_plural': 'โปรโมชั่น',
                'ordering': ['priority', '-created_at'],
            },
        ),
    ]
