# Generated by Django 6.0.7 on 2026-07-11 11:30

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('products', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Order',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('order_number', models.CharField(editable=False, max_length=30, unique=True)),
                ('recipient_name', models.CharField(max_length=150)),
                ('phone', models.CharField(max_length=20)),
                ('address', models.TextField()),
                ('subtotal', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('shipping_fee', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('grand_total', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('payment_method', models.CharField(choices=[('BANK_TRANSFER', 'โอนผ่านธนาคาร'), ('PROMPTPAY', 'พร้อมเพย์'), ('COD', 'เก็บเงินปลายทาง')], default='BANK_TRANSFER', max_length=20)),
                ('payment_status', models.CharField(choices=[('PENDING', 'รอตรวจสอบการชำระเงิน'), ('PAID', 'ชำระเงินแล้ว'), ('FAILED', 'ชำระเงินไม่สำเร็จ'), ('REFUNDED', 'คืนเงินแล้ว')], default='PENDING', max_length=20)),
                ('order_status', models.CharField(choices=[('NEW', 'คำสั่งซื้อใหม่'), ('CONFIRMED', 'ยืนยันคำสั่งซื้อแล้ว'), ('PROCESSING', 'กำลังเตรียมสินค้า'), ('SHIPPED', 'จัดส่งแล้ว'), ('COMPLETED', 'สำเร็จ'), ('CANCELLED', 'ยกเลิก')], default='NEW', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='OrderItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity', models.PositiveIntegerField(default=1)),
                ('unit_price', models.DecimalField(decimal_places=2, max_digits=10)),
                ('line_total', models.DecimalField(decimal_places=2, max_digits=10)),
                ('order', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='items', to='orders.order')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='order_items', to='products.product')),
            ],
        ),
    ]
