# Generated by Django 6.0.7 on 2026-07-18 02:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0002_wishlist'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='meta_description',
            field=models.CharField(blank=True, help_text='คำอธิบายสำหรับผลการค้นหา Google ไม่เกิน 155 ตัวอักษร', max_length=155),
        ),
        migrations.AddField(
            model_name='product',
            name='seo_title',
            field=models.CharField(blank=True, help_text='ชื่อที่แสดงบน Google ไม่เกิน 60 ตัวอักษร หากเว้นว่าง ระบบจะใช้ชื่อสินค้า', max_length=60),
        ),
    ]
